import = [
	# "~/.config/alacritty/themes/terminalapp.toml"
	# "~/.config/alacritty/themes/dracula.toml"
	# "~/.config/alacritty/themes/catpuccin-mocha.toml"
	# "~/.config/alacritty/themes/aura.toml"
	# "~/.config/alacritty/themes/carbonfox.toml"
	# "~/.config/alacritty/themes/moonfly.toml"
	# "~/.config/alacritty/themes/githubdarkdefault.toml"
	# "~/.config/alacritty/themes/everforest.toml"
	# "~/.config/alacritty/themes/vscode.toml"
	"~/.config/alacritty/themes/rosepine.toml"
]

[window]
option_as_alt="OnlyLeft"

[font]
normal = { family="FantasqueSansM Nerd Font Mono",  style="Regular" }
size = 14


[keyboard]
bindings = [
	{key= "k", mods= "Command", chars= "\u0002"} # Cmd+k sends Ctrl+b, to make tmux prefix easy on homerow.
]
