#!/bin/zsh


# Inside of ~/.zshrc: source ~/repos/dotfiles/zsh/zshrc


# Aliases

## kubernetes
alias k='kubectl'

## git
alias gitp='git push origin $(git branch --show-current)'

## laravel
alias art='php artisan'

alias lg='lazygit'

# Functions

## Terminal
function title {
    echo -ne "\033]0;"$*"\007"
}

# export $TERM="xterm-256color"
export EDITOR="hx"

# Setting editor to nvim breaks emacs-style keybindings for regular shell input. Restore that:
bindkey -e
